### ISSUE TITLE
[BUG] Ver 1.1.8-1 breaks some GTK3/4 apps (Gnome ToDo, Gnome Maps, Cheese) - On Hybrid Graphics configurations

### ISSUE THREAD

**Issue by brogers-propstream** [NVIDIA/egl-wayland#41] opened 2021-09-29 20:22 UTC
Expected behavior:

Launching Gnome ToDo, Gnome Maps, or Cheese functions and the app is displayed.

Actual behavior:

The apps are never launched

Debug Logs:

```
[3430410.735] wl_display@1.delete_id(36)
[3430410.749] wl_display@1.delete_id(37)
[3430410.753] wl_display@1.error(nil, 7, "failed to import supplied dmabufs: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a ")
13:01:41.382673                           Gdk:    DEBUG: [destroyed object]: error 7: failed to import supplied dmabufs: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a 

Gdk-Message: 13:01:41.382: Error flushing display: Protocol error
```

Workaround:

Rolling back to ver 1.1.7-1 resolved the issue entirely.

**Comment by cubanismo** [comment] 2021-09-29 20:32
Which GPU(s) were used in this testing?

**Comment by brogers-propstream** [comment] 2021-09-29 20:40
@cubanismo - Ah should've remembered that, my apologies.

I'm running a PRIME GPU setup.

Primary is my Ryzen 9 5900HS CPU's Radeon graphics. Secondary is my Nvidia 3070 Max-Q GPU.

I'm launching all apps in "non-prime" mode - meaning they should be using the integrated Radeon GPU. 

However, running in "prime" mode didn't change anything either. Still fails to launch with an identical error.

My OS is EndeavorOS/Arch and I'm fully up-to-date as of a few minutes ago.

**Comment by brogers-propstream** [comment] 2021-09-29 21:20
Per this reply - https://github.com/NVIDIA/egl-wayland/issues/40#issuecomment-930539832

I updated the description to suggest that this is specific to hybrid graphics.

**Comment by erik-kz** [comment] 2021-09-29 22:02
For the non-prime case, I wonder if it's still trying to use our EGL library instead of mesa's. Could you try running one of those applications with the environment variable __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json

**Comment by adamant-pwn** [comment] 2021-09-29 22:45
My setup is
```
egl-wayland version: 1.1.8-1
CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 3.200GHz 
GPU: NVIDIA GeForce RTX 3070 Mobile / Max-Q
GPU driver: NVIDIA 470.74
```
I had a similar problem and opened [this issue](https://gitlab.gnome.org/GNOME/gtk/-/issues/4287) on GNOME-gtk. Using environment variable `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json` fixed everything.

**Comment by cubanismo** [comment] 2021-09-30 18:47
I have a decent guess as to why this regressed now. Previously the egl-wayland code would only create displays for compositors that supported the EGLStreams wayland protocol extensions. In practice, this would fail for non-NV-driven wayland compositors and GLVND would presumably fall back to creating an EGLDisplay on some Mesa driver on such compositors. Now the code thinks it can render to any dmabuf-capable compositor, but in practice it only supports NV device-local buffers using NV-specific tiling formats, so happily reports support for the compositor but fails to present to it. Couple things to fix here:

-As of version 1.1.9, egl-wayland supports the wl_drm protocol on the compositor side, so we should be able to query the compositor for its DRM device and fail the display creation if binding that protocol fails (Non-NV device on the compositor side in that case) or if the device returned isn't an NV device.

-In the driver code, we should better handle surface creation such that it works in PRIME configs by creating non-device-local linear buffers that other devices can import if we don't see compatible tiled DRM format modifiers. Also, even if there are compatible format modifiers, but the device doesn't match (egl-wayland always runs on the first EGLDevice. It should probably use some better heuristic, e.g., pick the wl_drm-suggested device or use whatever comes out of [https://gitlab.freedesktop.org/wayland/wayland/-/issues/59](https://gitlab.freedesktop.org/wayland/wayland/-/issues/59)/[https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/8](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/8), but device mismatches can still occur), a tiled non-device-local buffer should be used. Unfortunately, there's not a great way to express the latter in the EGLStream EGLImage consumer/surface producer API right now, nor in the GBM API (Need a buffer constraints mechanism), so it might mean falling back to linear even for NV->NV GPU cases for the time being.

**Comment by cubanismo** [comment] 2021-09-30 19:14
I'll file internal NV bugs 3391989 (OSS egl-wayland fixes for the basic regression) and 3391982 (Actual cross-GPU/PRIME support in internal components) to track fixing this issue.

**Comment by bertin0** [comment] 2021-10-31 15:33
I just tried the changes on master (commit daab854) and I still need `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json` for alacritty to work. I think it fixed running firefox through xwayland though, so maybe there is some issue with alacritty being written in rust too.

**Comment by myyc** [comment] 2021-11-01 14:17
sorry to piggy back on this but it's also a problem with my CPU with non-integrated graphics (ryzen 5 5600x, nvidia 3060). the `__EGL_VENDOR_LIBRARY_FILENAMES` workaround fixes the affected apps (which for some reason aren't the same as the reporter's).

**Comment by dylanmtaylor** [comment] 2021-11-01 15:12
The __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json workaround is needed for me when launching gnome-boxes or amazon-workspaces.

**Comment by VarLad** [comment] 2021-11-03 10:27
@cubanismo One question
Considering that they'll fix stuff in the driver side
Would that be released as a minor release? or would it be another major release after a few months?

**Comment by cubanismo** [comment] 2021-11-03 15:59
As Erik mentioned above, we don't have any estimates for the driver-side fixes at the moment.

**Comment by solinium** [comment] 2021-11-29 04:39
With latest fedora updates it seems to be fixed for me. Would like other people to confirm this.

**Comment by flashrocket** [comment] 2022-04-10 16:31
also breaks mpv on ubuntu 22.04 beta. Hope the fixed driver is released soon.

**Comment by flashrocket** [comment] 2022-04-10 16:35
Hey @cubanismo Is there any update on the driver side fix?

**Comment by aisivan36** [comment] 2022-04-19 03:40
Gnome totem video player is broken and Cheese as well as gnome extensions cannot be opened on Optimus Wayland any fix of this?

**Comment by gzmorell** [comment] 2022-05-18 07:50
Version 1.1.9.1 on ubuntu 22.04  still has this problem

**Comment by bellini666** [comment] 2022-08-10 17:03
This issue is also present in Debian Sid as of writing this comment. Had this issue running gnome-console (kgx).

Running it with `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json kgx` fixes everything.

**Comment by davuses** [comment] 2022-08-24 04:59
Can confirm in Ubuntu22, the solution is adding variable `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json `

**Comment by erik-kz** [comment] 2022-09-02 14:03
This issue is fixed in version 1.1.10 and later. For earlier versions, yes, I suppose setting  __EGL_VENDOR_LIBRARY_FILENAMES is the easiest workaround.

**Closed** 2022-09-02 14:03 UTC

**Comment by mirao** [comment] 2022-10-14 11:30
The workaround works e.g. for app `cheese`.
But can I apply it somehow when I start settings of any Gnome Shell extension (e.g. [Clipboard Indicator](https://extensions.gnome.org/extension/779/clipboard-indicator/))?
```
gnome-shell[5189]: WL: error in client communication (pid 11332)
gjs[11332]: Error reading events from display: Protocol error
```
It doesn't matter if I start it over desktop Settings or over [web settings](https://extensions.gnome.org/), it fails with the mentioned error.
I'm using Ubuntu 22.04, libnvidia-egl-wayland1 1.1.9-1.1

**Comment by Schneegans** [comment] 2022-10-14 14:36
I think you should be able to open the extensions app with this:

```bash
export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json
gjs /usr/share/gnome-shell/org.gnome.Shell.Extensions & gnome-extensions-app
```

**Comment by mirao** [comment] 2022-10-17 08:32
@Schneegans Works well, thank you very much.

**Comment by TheComputerGuy96** [comment] 2022-11-03 07:17
This error still happens with Vulkan applications:
```
$ prime-run vkcube-wayland 
Selected GPU 0: NVIDIA GeForce GTX 1650 Ti, type: DiscreteGpu 
[destroyed object]: error 7: failed to import supplied dmabufs: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a
```
