### ISSUE TITLE
Firefox randomly crashes with "Exiting due to channel error"

### ISSUE THREAD

**Issue by git-bruh** [NVIDIA/egl-wayland#73] opened 2022-12-02 10:18 UTC
Firefox seems to randomly exit during normal usage, say while opening the downloads menu,  middle-clicking or right-clicking. It's not reproducible at all though, happens like once in 2 days or usage.

Not sure if this is an NVIDIA related bug or a firefox bug, but I've attached both sway and firefox logs so someone more familiar with this stuff can comment.

`nvidia 525.60.11` (Happened on older versions aswell)
`sway 1.8-rc1` (Happened on older versions aswell)
`gtk+3 3.24.34`
`wlroots 0.16.0`
`wayland 1.21.0`

Sway log: https://bugzilla.mozilla.org/attachment.cgi?id=9306380
Firefox log: https://bugzilla.mozilla.org/attachment.cgi?id=9306381

Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1795663

**Comment by vieiraa** [comment] 2023-08-11 17:11
I'm having a similar problem, and it is very reproducible. All I have to do to trigger the crash is watch a few minutes of a Youtube video in fullscreen and then exit fullscreen.

I'm using GNOME 44, firefox 116.0.2 and nvidia 535.98.

**Comment by teatwig** [comment] 2023-09-11 21:44
I have the same problem. Gnome 44, Firefox 117, Nvidia 535.104.05.
It's not consistently reproducible but most of the time happens when unmaximizing the window.

**Comment by sontjer** [comment] 2023-09-13 00:37
> I'm having a similar problem, and it is very reproducible. All I have to do to trigger the crash is watch a few minutes of a Youtube video in fullscreen and then exit fullscreen.
> 
> I'm using GNOME 44, firefox 116.0.2 and nvidia 535.98.

I have experienced the same as you described. Wayland- NV Hardware acceleration-Firefox 117.  X11 all fine.

**Comment by erik-kz** [comment] 2023-09-13 14:46
I've seen similar crashes sporadically on Intel hardware, so I'm not sure that this is NVIDIA specific.

**Comment by AlynxZhou** [comment] 2023-09-20 07:06
I got crash most likely closing a tab with a video stream, my firefox crash report (https://crash-stats.mozilla.org/report/index/8e4cc429-9756-4abc-bcfd-8761f0230920) says it happens in egl-wayland.

**Comment by erik-kz** [comment] 2023-09-20 13:53
@AlynxZhou I have a theory about that explained in my last comment here https://bugzilla.mozilla.org/show_bug.cgi?id=1850285

Unfortunately I cannot reproduce the crash to confirm. Would you be willing to build egl-wayland with the patch linked on that bug report to see if it fixes things?

**Comment by AlynxZhou** [comment] 2023-09-20 13:54
> @AlynxZhou I have a theory about that explained in my last comment here https://bugzilla.mozilla.org/show_bug.cgi?id=1850285
> 
> Unfortunately I cannot reproduce the crash to confirm. Would you be willing to build egl-wayland with the patch linked on that bug report to see if it fixes things?

No problem!

**Comment by AlynxZhou** [comment] 2023-09-20 14:21
@erik-kz I think it fixes the crash, but I may need more test because the crash does not happen every time.

I think I need to logout my Wayland session and re-login to load the patched version of egl-wayland, right?

What I tried:

- Patch and install egl-wayland, `killall firefox`, re-run firefox, open some video tab and play for a while, drag it out, drag it back, crash.
- Patch and install egl-wayland, logout Wayland session, re-login, start firefox, open some video tab and play for a while, drag it out, drag it back, NO crash.
- Install the NON-patched egl-wayland, logout Wayland session, re-login, start firefox, open some video tab and play for a while, drag it out, drag it back, crash.

I'll continue trying the patched version tomorrow and if I got crash I'll tell you ASAP.

**Comment by AlynxZhou** [comment] 2023-09-20 14:26
Oh no, my firefox just crashed with the patched egl-wayland, I just drag a video tab out and let it play for some minutes and drag it back.

**Comment by AlynxZhou** [comment] 2023-09-20 14:28
This time the crash backtrace is a little bit different: https://crash-stats.mozilla.org/report/index/e0728872-f710-4ea2-80fa-911570230920

**Comment by erik-kz** [comment] 2023-09-20 18:12
Thank you very much for testing. Just to confirm, did you apply the patch on top of the git master branch? In particular, did your build also have this commit https://github.com/NVIDIA/egl-wayland/commit/3ead05d4587991b75dc704444b1b1365c08af5ce ?

**Comment by AlynxZhou** [comment] 2023-09-21 00:22
> Thank you very much for testing. Just to confirm, did you apply the patch on top of the git master branch? In particular, did your build also have this commit [3ead05d](https://github.com/NVIDIA/egl-wayland/commit/3ead05d4587991b75dc704444b1b1365c08af5ce) ?

No, I build it against egl-wayland in Arch's official repo, will try master today.

**Comment by AlynxZhou** [comment] 2023-09-21 02:17
This time it looks fine, but please wait for more tests today. I'll tell you if it crashes again.

**Comment by AlynxZhou** [comment] 2023-09-21 06:35
I think this time it fixes this bug. I've tested a lot.

**Comment by erik-kz** [comment] 2023-09-21 16:47
Awesome, I'll get the patch checked in then. Again, thank you so much for your help.

**Comment by AlynxZhou** [comment] 2023-09-25 09:27
> Awesome, I'll get the patch checked in then. Again, thank you so much for your help.

This is one of the most annoying problems on my Wayland experience with NVIDIA (well, another one is https://gitlab.freedesktop.org/xorg/xserver/-/issues/1317, but at least it won't crash and for me only happens with Slack), I am so grateful for all your works on making NVIDIA users' Wayland experience better including this one 😸️

**Comment by CosmicFusion** [comment] 2023-10-18 18:10
Without this patch, firefox crashes when going fullscreen with nv hwaccel 100% of the time

With this patch applied, firefox plays fullscreen video with nv hwaccel but messing around with the video causes a crash

Definitely an improvement

**Closed** 2024-04-13 23:47 UTC
