### ISSUE TITLE
Version 1.1.14 is killing my firefox and brave

### ISSUE THREAD

**Issue by dmaliog** [NVIDIA/egl-wayland#117] opened 2024-07-18 23:18 UTC
Version 1.1.14 is killing my firefox and brave.
 firefox no longer works and in brave the title disappears when maximizing

⋊> ~ on master ⨯ inxi -G                                                                                                                             04:16:42
Graphics:
  Device-1: NVIDIA GP102 [GeForce GTX 1080 Ti] driver: nvidia v: 555.58.02
  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 24.1.1
    compositor: kwin_wayland driver: X: loaded: nvidia gpu: nvidia
    resolution: 2560x1440
  API: EGL v: 1.5 drivers: nvidia,swrast,zink
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 555.58.02
    renderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
  API: Vulkan v: 1.3.279 dri

OS: EndeavourOS Linux x86_64 
Host: B550 GAMING X V2 
Kernel: 6.10.0-1-mainline 
Uptime: 13 mins 
Packages: 1792 (pacman), 4 (flatpak), 4 (snap) 
Shell: fish 3.7.1 
Resolution: 2560x1440 
DE: Plasma 6.1.2 
WM: kwin 
Theme: Breeze-Dark [GTK2], Breeze [GTK3] 
Icons: Papirus-Dark [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 5 5600 (12) @ 3.500GHz 
GPU: NVIDIA GeForce GTX 1080 Ti 
Memory: 3686MiB / 32000MiB 

I had to roll back...

**Comment by ionenwks** [comment] 2024-07-19 00:32
Was trying to reproduce this in Gentoo given we've barely just added 1.1.14, but firefox-128.0 was working fine w/ plasma 6. Turns out it's because we do MOZ_ENABLE_WAYLAND=1 by default (aka native wayland), issues only manifest when that is disabled (=0) and it uses xwayland.

Output looks like this when disabled:
```
$ MOZ_ENABLE_WAYLAND=0 firefox
[GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1@67: error 4: explicit sync is used, but no acquire point is set

ExceptionHandler::GenerateDump attempting to generate:/home/evan/.mozilla/firefox/l7ean1pl.default-release/minidumps/66b81674-6605-3a4f-b1a8-927628824011.dmp
ExceptionHandler::GenerateDump cloned child 2918
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::GenerateDump minidump generation succeeded
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
```
Does work fine if go back to 1.1.13.

fwiw, that was in a slightly outdated virtual machine w/ passthrough to a GTX 1070 with plasma-6.1.2, xwayland-23.2.6, albeit did update nvidia's drivers to 555.58.02.

So, as a workaround may want to try to set MOZ_ENABLE_WAYLAND=1.

Have not tried Brave, but google chrome seemed normal.

**Comment by ToadKing** [comment] 2024-07-19 00:33
I'm having similar issues with 1.1.14 on Firefox Nightly. After browsing for 10-15 minutes the browser would crash, but all the crash traces seem to be different sometimes.

Exmpales:
https://crash-stats.mozilla.org/report/index/9eafa8d4-7ee1-4e8b-b1f5-2caad0240718
https://crash-stats.mozilla.org/report/index/2ff93945-580c-4a67-86c2-ba5b50240718

System info:
Distro: Arch
Kernel: 6.9.10-arch1-1
GPU: GeForce RTX 2070
Nvidia driver version: 555.58.02
DE: KDE Plasma 6.1.2

**Comment by ToadKing** [comment] 2024-07-19 00:40
@ionenwks I think my crash might be different because on my system I'm already using native Wayland for Firefox.

**Comment by ionenwks** [comment] 2024-07-19 00:47
> @ionenwks I think my crash might be different because on my system I'm already using native Wayland for Firefox.

Was just experimenting further, and you're right. Disabling that just makes it crash *earlier*, after working for a bit.

**Comment by amshafer** [comment] 2024-07-19 01:37
This is a duplicate of #110

**Closed by amshafer** 2024-07-19 01:37 UTC

**Comment by ToadKing** [comment] 2024-07-20 20:23
I think this might be worth re-opening because the issue described in #110 was fixed in Firefox Nightly builds but crashes are still happening. See https://bugzilla.mozilla.org/show_bug.cgi?id=1908825 specifically the comments by Jan Alexander Steffens.

**Comment by testsnake** [comment] 2024-07-22 05:44
The patch for the firefox bug mentioned in #110 was supposedly backported to [128.0-2](https://gitlab.archlinux.org/archlinux/packaging/packages/firefox/-/commit/a98925a6a72a94fdd46f84ba76ec9be25da682aa) on arch, and I'm still experiencing the issue on 1.1.14, and not experiencing it on 1.1.13.

**Comment by belegdol** [comment] 2024-07-22 10:41
Same here. Fedora 128.0-2 fixed some issues but Firefox is still crashing.

**Comment by testsnake** [comment] 2024-07-22 16:28
Looks like Arch has reverted to 1.1.13 for now due to the issue. https://gitlab.archlinux.org/archlinux/packaging/packages/egl-wayland/-/commit/e385ef755321b1f9dfb1d4a3972d6d96d7ef94c9

**Comment by ionenwks** [comment] 2024-07-22 22:01
We did so as well in Gentoo early on for the record (1.1.14 still exists in our repo, but it's masked so it doesn't get installed unless users explicitly opt-in for testing it). Feel it's reasonable for now given issues seem to be piling up alongside #118

**Comment by ToadKing** [comment] 2024-08-01 16:42
@amshafer There's been more investigation on the Firefox side and they seem to think the issue is not in Firefox.

https://bugzilla.mozilla.org/show_bug.cgi?id=1908825#c31

> Thanks. According to the log it doesn't look like a Firefox bug. Let's see:
> 
> wl_buffer#227 is created here by GL as dmabuf buffer (Firefox doesn't create dmabuf buffers at all) and it has explicit sync set (again - Firefox doesn't set explicit points). This looks like MESA or egl-wayland code:
> 
>     [Parent 3270: Renderer]: D/WidgetWayland nsWindow::LockSurface()
>     [1025134.831]  -> wp_linux_drm_syncobj_manager_v1#54.import_timeline(new id wp_linux_drm_syncobj_timeline_v1#228, fd 247)
>     [1025134.850]  -> wp_linux_drm_syncobj_manager_v1#54.import_timeline(new id wp_linux_drm_syncobj_timeline_v1#214, fd 249)
>     [1025134.870]  -> wp_linux_drm_syncobj_manager_v1#54.import_timeline(new id wp_linux_drm_syncobj_timeline_v1#208, fd 250)
>     [1025134.889]  -> wp_linux_drm_syncobj_manager_v1#54.import_timeline(new id wp_linux_drm_syncobj_timeline_v1#201, fd 251)
>     [1025136.884] {Default Queue}  -> zwp_linux_dmabuf_v1#49.create_params(new id zwp_linux_buffer_params_v1#236)
>     [1025136.894] {Default Queue}  -> zwp_linux_buffer_params_v1#236.add(fd 252, 0, 0, 10240, 50331648, 6316052)
>     [1025136.900] {Default Queue}  -> zwp_linux_buffer_params_v1#236.create_immed(new id wl_buffer#237, 2560, 1382, 875713089, 0)
>     [1025136.904] {Default Queue}  -> zwp_linux_buffer_params_v1#236.destroy()
>     [1025136.911] {Default Queue}  -> wl_surface#67.attach(wl_buffer#237, 0, 0)
>     [1025136.923]  -> wp_linux_drm_syncobj_surface_v1#70.set_acquire_point(wp_linux_drm_syncobj_timeline_v1#72, 0, 508)
>     [1025136.927]  -> wp_linux_drm_syncobj_surface_v1#70.set_release_point(wp_linux_drm_syncobj_timeline_v1#201, 0, 1)
>     [1025136.931] {Default Queue}  -> wl_surface#67.damage(0, 0, 2560, 1382)
>     [1025136.934] {Default Queue}  -> wl_surface#67.commit()
> 
> So wl_buffer#237 is internal GL buffer used for front/back buffer, the size indicates it too (2560, 1382):
> 
>     [1024915.497] {Default Queue}  -> zwp_linux_buffer_params_v1#114.create_immed(new id wl_buffer#227, 2560, 1440, 875713089, 0)
> 
> Note that similar buffer (#221) is also allocated for rendering with the same size:
> 
>     [Parent 3270: Renderer]: D/WidgetWayland nsWindow::LockSurface()
>     [1025149.994] {Default Queue}  -> zwp_linux_dmabuf_v1#49.create_params(new id zwp_linux_buffer_params_v1#193)
>     [1025150.005] {Default Queue}  -> zwp_linux_buffer_params_v1#193.add(fd 249, 0, 0, 10240, 50331648, 6316052)
>     [1025150.011] {Default Queue}  -> zwp_linux_buffer_params_v1#193.create_immed(new id wl_buffer#221, 2560, 1382, 875713089, 0)
>     [1025150.016] {Default Queue}  -> zwp_linux_buffer_params_v1#193.destroy()
>     [1025150.022] {Default Queue}  -> wl_surface#67.attach(wl_buffer#221, 0, 0)
>     [1025150.036]  -> wp_linux_drm_syncobj_surface_v1#70.set_acquire_point(wp_linux_drm_syncobj_timeline_v1#72, 0, 509)
>     [1025150.040]  -> wp_linux_drm_syncobj_surface_v1#70.set_release_point(wp_linux_drm_syncobj_timeline_v1#208, 0, 1)
>     [1025150.044] {Default Queue}  -> wl_surface#67.damage(0, 0, 2560, 1382)
>     [1025150.047] {Default Queue}  -> wl_surface#67.commit()
> 
> And now the error sequence:
> 
>     [Parent 3270: Renderer]: D/WidgetWayland nsWindow::LockSurface()
>     [1063978.115] {Default Queue}  -> wl_surface#67.attach(wl_buffer#221, 0, 0)  << attach
>     [1063978.134]  -> wp_linux_drm_syncobj_surface_v1#70.set_acquire_point(wp_linux_drm_syncobj_timeline_v1#72, 0, 5097)
>     [1063978.140]  -> wp_linux_drm_syncobj_surface_v1#70.set_release_point(wp_linux_drm_syncobj_timeline_v1#208, 0, 1151) << set sync
>     [1063978.145] {Default Queue}  -> wl_surface#67.damage(0, 0, 2560, 1382) << Set damage
>     [1063978.149] {Default Queue}  -> wl_surface#67.commit() << commit
>     [...]
>     [1063982.605] {Default Queue}  -> wl_surface#67.frame(new id wl_callback#241) << frame callback request
>     [1063982.609] {Default Queue}  -> wl_surface#67.commit()  << frame callback request commit
> 
>     [Parent 3270: Renderer]: D/WidgetWayland nsWindow::LockSurface()
>     [1063989.819] {Default Queue}  -> wl_surface#67.attach(wl_buffer#237, 0, 0) << attach
> 
>     << missing sync point set, damage and commit. 
> 
>     [1063994.651] {Default Queue}  -> wl_surface#67.frame(new id wl_callback#241) << frame callback request
>     [1063994.656] {Default Queue}  -> wl_surface#67.commit()  << frame callback request commit. 
> 
>     But it also takes attach(wl_buffer#237) but without sync point so kaboom:
> 
>     [1063994.793] {Display Queue} wl_display#1.error(wp_linux_drm_syncobj_surface_v1#70, 4, "explicit sync is used, but no acquire point is set")
>     [GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1#70: error 4: explicit sync is used, but no acquire point is set
> 
> As we see, for wl_buffer#221 it's attached, set damage size damage(0, 0, 2560, 1382) and commited.
> wl_buffer#237 it's only attached and nothing else. As we see we're missing damage set here and commit.
> Only frame callback commit is performed and that leads to protocol error as it also use already attached buffer without sync.
> 
> From the log it looks like egl-wayland (or someone else) attaches wl_buffer#237 even if it's not going to be committed which leads to the missing sync point error.
> 
> There's the Firefox core where it happens in Render Thread:
> 
> https://searchfox.org/mozilla-central/rev/669fac9888b173c02baa4c036e980c0c204dfe02/gfx/webrender_bindings/RenderCompositorEGL.cpp#164
> 
>     #ifdef MOZ_WIDGET_GTK
>       // Rendering on Wayland has to be atomic (buffer attach + commit) and
>       // wayland surface is also used by main thread so lock it before
>       // we paint at SwapBuffers().
>       UniquePtr<MozContainerSurfaceLock> lock;
>       if (auto* gtkWidget = mWidget->AsGTK()) {
>         lock = gtkWidget->LockSurface();
>       }
>     #endif
>       gl()->SwapBuffers();
> 
> As you can see we just call eglSwapBuffers().
> 
> So definitely not a Firefox bug (unfortunately as it looks like a clear/simple one and may be quickly fixed if it's in Firefox).

Can this bug be re-opened?
