### ISSUE TITLE
Update to nvidia 560.28.0 and egl 1.1.14

### ISSUE THREAD

**Issue by dmaliog** [NVIDIA/egl-wayland#119] opened 2024-07-24 03:40 UTC
With the new driver from nvidia 560.28.0 with egl 1.1.14 everything works (except opera with wayland and some other applications related to wayland), and with 1.1.13 the kde environment starts to freeze the panel and desktop and crash some applications.

**Comment by dmaliog** [comment] 2024-07-24 03:43
The most important thing is that with the latest drivers, the kde shell itself in conjunction with egl 1.1.14 works well, and I think the applications will adjust later

**Comment by dmaliog** [comment] 2024-07-24 03:47
In the screen settings the Adaptive synchronization option appeared, I set it to Auto mode and opera began to work with wayland

**Comment by thesword53** [comment] 2024-07-24 19:22
With `egl-wayland`<1.1.14 and 560 drivers every EGL Wayland application will fallback to Zink or LLVMpipe.

**Comment by amshafer** [comment] 2024-07-24 20:23
This was fixed by commit https://github.com/NVIDIA/egl-wayland/commit/3f673dcb7c9b20145ca74b359f62e65c948a7f21, which is why it works in 1.1.14

**Comment by Vash63** [comment] 2024-07-26 09:49
> Can you please confirm this tag fixes the issue? https://github.com/amshafer/egl-wayland/releases/tag/1.1.13.1

`eglinfo` shows all NV with this fork, but Proton games are still printing a black screen almost every launch (strangely every once in a while I can get one to boot, haven't figured out why).

**Comment by amshafer** [comment] 2024-07-26 13:53
Please provide details with reports like this, which compositor, games, any logs, etc so we can try to reproduce.

I'm assuming you did this but just double checking: you did restart your desktop after installing the `1.1.13.1` tag I linked above correct? You have to restart Xwayland for it to take effect.

**Comment by amshafer** [comment] 2024-07-26 14:29
Argh sorry, the tag I gave you hit an issue with meson not properly updating the `libnvidia-egl-wayland.so.1` symlink causing it to use the old library version. I've updated the tag to fix that, can you please try again? 

4ee8b84 - https://github.com/amshafer/egl-wayland/releases/tag/1.1.13.1

**Comment by Vash63** [comment] 2024-07-26 15:30
I've duplicated it across a number of games. Used the Quake 1 remaster in Proton as an easy test since it boots very quickly. 

Tested in both Gnome and KDE on Wayland and with your latest update on Arch, latest versions of everything. I sent logs to ahuillet earlier, I'm not at that computer at the moment to upload them here.

**Comment by Vash63** [comment] 2024-07-29 20:58
I'm having the black screen / hang issue even with 1.1.14, just to be clear. I've both tried the "1.1.13" shipped included with the 560 drivers, your earlier 1.1.13.1 tag (on the fork) and 1.1.14, it does not seem to matter. I have not yet tried the "new" 1.1.13.1 on this repo, if it's different than the earlier one from your fork I could try that, but is 1.1.14 supposed to be working? Should we be waiting for a 1.1.14.1 with a similar fix on the newer branch?

**Comment by carbonXIII** [comment] 2024-07-30 18:00
Just in case anyone else runs into this, I also needed 11386ccd5cb82c245f194abbfe63ab2dffc9f810 on top of 1.1.13.1 in order for this to load with somewhat recent wlroots.

**Comment by Vash63** [comment] 2024-08-11 19:25
1.1.15 + NV560.31.02 fixed all issues for me.

**Closed** 2024-08-12 15:47 UTC
